spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 2274094e86ac40f6a401883715ae539d14be2e1dfe4552cfbb71b768ae8ea452
            client-secret: b5245ca84327ce890372c69745c639c8c0dd9a5916ec3f7fb5fed5485e8d8433
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            scope: user_info
          gitee2:
            client-id: d67c84dd1f4af710550ec3835cdcc1db79c8728069b91fcb10ba0f59e0d83ce3
            client-secret: 722818c3564f259bfbf7a424d04d8d962cafc7e5e32443b7182c2c1f70616f8e
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            scope: user_info
          wechat:
            # 可以去试一下沙箱
            # 公众号服务号 appid
            client-id: wxdf9033184b238e7f
            # 公众号服务号 secret
            client-secret: bf1306baaa0d874457db15eb02d68df5
            # oauth2 login 用 '{baseUrl}/login/oauth2/code/{registrationId}' 会自动解析
            # oauth2 client 写你业务的链接即可
            authorization-grant-type: authorization_code
            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: snsapi_userinfo
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name
          gitee2:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name
          wechat:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo

