spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-name: 码云
            client-id: 2274094e86ac40f6a401883715ae539d14be2e1dfe4552cfbb71b768ae8ea452
            client-secret: b5245ca84327ce890372c69745c639c8c0dd9a5916ec3f7fb5fed5485e8d8433
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            scope: user_info
          wechat-web:
            client-name: 微信网页授权
            # 可以去试一下沙箱
            # 公众号服务号 appid
            client-id: wxdf9033184b238e7f
            # 公众号服务号 secret
            client-secret: bf1306baaa0d874457db15eb02d68df5
            # oauth2 login 用 '{baseUrl}/login/oauth2/code/{registrationId}' 会自动解析
            # oauth2 client 写你业务的链接即可
            authorization-grant-type: authorization_code
            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: snsapi_userinfo
          wechat-web-login:
            client-name: 微信
            client-id: xxxx
            client-secret: xxxxxxxxxxxx
            authorization-grant-type: authorization_code
            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: snsapi_login
          work-wechat-scan:
            client-name: 企业微信
            #todo 企业微信 CORPID
            client-id: wwa70dc5b6e56936e1
            #todo 企业微信对应应用的secret
            client-secret:  nvzGI4Alp3zS7rfOYAlFs-BZUc3TtPtKbnfTEets5W8
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name
          wechat-web:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
          wechat-web-login:
            authorization-uri: https://open.weixin.qq.com/connect/qrconnect
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
          work-wechat-scan:
            authorization-uri: https://open.work.weixin.qq.com/wwopen/sso/qrConnect
            token-uri: https://qyapi.weixin.qq.com/cgi-bin/gettoken
            user-info-uri: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo