spring:
  security:
    oauth2:
      client:
        registration:
            ## 测试oauth2 client 模式
          gitee-client:
            client-id: 0356769a213a442b638de4f5563bd61406ac5d6883debc0578eb61addad8999b
            client-secret: fb551e14cef3e3ffc8865f6e681565b0332d6a4a0d9bd9653b7beae304fa59de
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/oauth2/jwks
            client-authentication-method: POST
            scope: user_info
          wechat:
            # 可以去试一下沙箱
            # 公众号服务号 appid
            client-id: wxdf9033184b238e7f
            # 公众号服务号 secret
            client-secret: bf1306baaa0d874457db15eb02d68df5
            # oauth2 client 写你业务的链接即可
            authorization-grant-type: authorization_code
            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: snsapi_userinfo
        provider:
          gitee-client:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name
          wechat:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo

