server:
  port: 8082
# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: debug
# 自定义jwt 配置
jwt:
  cert-info:
    public-key-location: pub.cer
  claims:
    issuer: https://felord.cn
    expires-at: 604800
