logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          felord:
            client-id: felord
            # hmac sha 256 有长度要求
            client-secret: 226ab006e9494b0e84893cd7b402cd8e
            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_jwt
            client-authentication-method: client_secret_basic
            scope: message.read,message.write,openid
        provider:
          felord:
            issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: resource-server
          uri: http://localhost:8003
          predicates:
            - Path=/resource/**
          filters:
#            - StripPrefix=1
            - TokenRelay
