spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 2274094e86ac40f6a401883715ae539d14be2e1dfe4552cfbb71b768ae8ea452
            client-secret: b5245ca84327ce890372c69745c639c8c0dd9a5916ec3f7fb5fed5485e8d8433
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            scope: user_info
          wechat:
            # 可以去试一下沙箱
            # 公众号服务号 appid
            client-id: wxdf9033184b238e7f
            # 公众号服务号 secret
            client-secret: bf1306baaa0d874457db15eb02d68df5
            # oauth2 login 用 '{baseUrl}/login/oauth2/code/{registrationId}' 会自动解析
            # oauth2 client 写你业务的链接即可
            authorization-grant-type: authorization_code
            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: snsapi_userinfo
          felord:
            client-id: felord
            client-secret: secret
            #            isValidRedirectUri
            #            http://127.0.0.1:8082/oauth2/authorization/felord
            #todo        redirect-uri:  '{baseUrl}/foo/bar' 错误的写法  根据oauth2协议localhost不可被解析
            redirect-uri:  'http://127.0.0.1:8082/login/oauth2/code/{registrationId}'
#            redirect-uri:  'http://127.0.0.1:8082/foo/bar'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: userinfo,message.read,message.write
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name
          wechat:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
          felord:
            #todo       provider 尽量用域名  不建议用localhost或者IP  而且要和well-known接口中保持一致
            issuer-uri: http://localhost:9000
            user-info-uri: http://localhost:9000/oauth2/user
            user-name-attribute: name
