spring:
  security:
    oauth2:
      client:
        registration:
          felord:
            client-id: felord
            client-secret: secret
            #            isValidRedirectUri
            #            http://127.0.0.1:8082/oauth2/authorization/felord
            #todo        redirect-uri:  '{baseUrl}/foo/bar' 错误的写法  根据oauth2协议localhost不可被解析
            #            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            redirect-uri:  'http://127.0.0.1:8082/foo/bar'
            authorization-grant-type: authorization_code
            client-authentication-method: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
            scope: message.read,message.write
        provider:
          felord:
            #todo       provider 尽量用域名  不要用localhost或者IP  而且要和well-known接口中保持一致
            issuer-uri: http://localhost:9000
#           issuer-uri 可以简化下面的配置
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            token-uri: http://localhost:9000/oauth2/token
#            user-info-uri: http://your-userinfo-endpoiont
#            user-name-attribute: username
#            user-info-authentication-method: GET
